#!/usr/bin/env python

import sys

from packml_gui.packml import Packml
from rqt_gui.main import Main

plugin = 'packml_gui.packml.Packml'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin, plugin_argument_provider=Packml.add_arguments))
