# Request a reset of statistics published on stats topic.  This service
# should be called occasionally to prevent variable overflow (although the
# variables are suitably large).
# This service can also be used to track statistics on a remote system.  The
# "last stats" represent the stats before the reset call.  These stats can be
# "added" to previous calls as required

---
# State machine response
bool success         # True if reset was successful
Stats last_stat      # Last statistic before reset applied.
